# Generated by Django 4.2 on 2023-05-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
