# Generated by Django 4.1.7 on 2023-04-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'female')], default='1', max_length=1),
        ),
    ]
