# Generated by Django 4.2 on 2023-05-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', related_query_name='Offer', to='api.company'),
        ),
    ]
