# Generated by Django 4.1.7 on 2023-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
