# Generated by Django 4.2 on 2023-05-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_offer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.offer'),
        ),
    ]
