# Generated by Django 4.1.7 on 2023-04-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_location_remove_company_location_company_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Location',
            new_name='location',
        ),
    ]
