# Generated by Django 4.1.7 on 2023-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_offer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
